-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-09-16 21:20:25 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL rcl_logical_schema_output.txt

--student id: G053
--student name: Yasna Bezhan, Minh Ngo, Gabriel Garriock

DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE book_copy CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE cata_author CASCADE CONSTRAINTS;

DROP TABLE cata_isbn CASCADE CONSTRAINTS;

DROP TABLE cata_subject CASCADE CONSTRAINTS;

DROP TABLE catalogue CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE isbn CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reserve CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE author (
    author_code       CHAR(4) NOT NULL,
    author_first_name VARCHAR2(64) NOT NULL,
    author_last_name  VARCHAR2(64) NOT NULL
);

COMMENT ON COLUMN author.author_code IS
    'Authors code';

COMMENT ON COLUMN author.author_first_name IS
    'Authors given name';

COMMENT ON COLUMN author.author_last_name IS
    'Authors surname name';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( author_code );

CREATE TABLE book_copy (
    book_copy_num              CHAR(4) NOT NULL,
    book_copy_id               CHAR(4) NOT NULL,
    branch_code                CHAR(3) NOT NULL,
    book_copy_purchase_price   NUMBER(10, 2) NOT NULL,
    isbn_value                 CHAR(13) NOT NULL,
    book_copy_available_status CHAR(1) NOT NULL
);

ALTER TABLE book_copy
    ADD CHECK ( book_copy_available_status IN ( 'A', 'N', 'O', 'R' ) );

COMMENT ON COLUMN book_copy.book_copy_num IS
    'book number (surrogate PK)';

COMMENT ON COLUMN book_copy.book_copy_id IS
    'Book copy ID';

COMMENT ON COLUMN book_copy.branch_code IS
    'Branch Code';

COMMENT ON COLUMN book_copy.book_copy_purchase_price IS
    'Book copy purchase price';

COMMENT ON COLUMN book_copy.isbn_value IS
    'ISBN digit';

COMMENT ON COLUMN book_copy.book_copy_available_status IS
    'Book copy avalibility status';

ALTER TABLE book_copy ADD CONSTRAINT book_copy_pk PRIMARY KEY ( book_copy_num );

ALTER TABLE book_copy ADD CONSTRAINT book_copy_branch_c_bc_id_un UNIQUE ( branch_code,
                                                                          book_copy_id );

CREATE TABLE borrower (
    borrower_id          CHAR(4) NOT NULL,
    borrower_first_name  VARCHAR2(64) NOT NULL,
    borrower_last_name   VARCHAR2(64) NOT NULL,
    borrower_status      CHAR(1) NOT NULL,
    borrower_contact_num CHAR(10),
    branch_code          CHAR(3) NOT NULL,
    class_id             CHAR(4) NOT NULL
);

ALTER TABLE borrower
    ADD CONSTRAINT "BORROWER_STATUS VALUE" CHECK ( borrower_status IN ( 'B', 'P' ) );

COMMENT ON COLUMN borrower.borrower_id IS
    'Borrower ID';

COMMENT ON COLUMN borrower.borrower_first_name IS
    'Borrowers first name';

COMMENT ON COLUMN borrower.borrower_last_name IS
    'Borrowers first name';

COMMENT ON COLUMN borrower.borrower_status IS
    'status of borrower';

COMMENT ON COLUMN borrower.borrower_contact_num IS
    'Borrowers contact phone number';

COMMENT ON COLUMN borrower.branch_code IS
    'Branch Code';

COMMENT ON COLUMN borrower.class_id IS
    'Id of class';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( borrower_id );

CREATE TABLE branch (
    branch_code      CHAR(3) NOT NULL,
    branch_name      VARCHAR2(256) NOT NULL,
    branch_address   VARCHAR2(256) NOT NULL,
    branch_phone_num CHAR(10) NOT NULL,
    lga_code         CHAR(10) NOT NULL,
    manager_id       CHAR(10) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'Branch Code';

COMMENT ON COLUMN branch.branch_name IS
    'Branch name';

COMMENT ON COLUMN branch.branch_address IS
    'Branch Address';

COMMENT ON COLUMN branch.branch_phone_num IS
    'Branch phone number';

COMMENT ON COLUMN branch.lga_code IS
    'LGA code';

COMMENT ON COLUMN branch.manager_id IS
    'Manager id';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( branch_code );

CREATE TABLE cata_author (
    author_code CHAR(4) NOT NULL,
    cata_ddnum  VARCHAR2(64) NOT NULL
);

COMMENT ON COLUMN cata_author.author_code IS
    'Authors code';

COMMENT ON COLUMN cata_author.cata_ddnum IS
    'Catalogue items Dewey Decimal Number';

ALTER TABLE cata_author ADD CONSTRAINT cata_author_pk PRIMARY KEY ( author_code,
                                                                    cata_ddnum );

CREATE TABLE cata_isbn (
    cata_ddnum VARCHAR2(64) NOT NULL,
    isbn_value CHAR(13) NOT NULL
);

COMMENT ON COLUMN cata_isbn.cata_ddnum IS
    'Catalogue items Dewey Decimal Number';

COMMENT ON COLUMN cata_isbn.isbn_value IS
    'ISBN digit';

ALTER TABLE cata_isbn ADD CONSTRAINT cata_isbn_pk PRIMARY KEY ( cata_ddnum,
                                                                isbn_value );

CREATE TABLE cata_subject (
    cata_ddnum VARCHAR2(64) NOT NULL,
    sub_id     CHAR(4) NOT NULL
);

COMMENT ON COLUMN cata_subject.cata_ddnum IS
    'Catalogue items Dewey Decimal Number';

COMMENT ON COLUMN cata_subject.sub_id IS
    'Subject ID';

ALTER TABLE cata_subject ADD CONSTRAINT cata_subject_pk PRIMARY KEY ( sub_id,
                                                                      cata_ddnum );

CREATE TABLE catalogue (
    cata_ddnum            VARCHAR2(64) NOT NULL,
    cata_title            VARCHAR2(256) NOT NULL,
    cata_description      VARCHAR2(2048) NOT NULL,
    cata_publication_year DATE NOT NULL,
    cata_edition          VARCHAR2(64),
    cata_num_page         NUMBER(6) NOT NULL,
    cata_language         VARCHAR2(64) NOT NULL,
    cata_note             VARCHAR2(2048),
    publisher_code        CHAR(4) NOT NULL
);

COMMENT ON COLUMN catalogue.cata_ddnum IS
    'Catalogue items Dewey Decimal Number';

COMMENT ON COLUMN catalogue.cata_title IS
    'Catalogue entrys title';

COMMENT ON COLUMN catalogue.cata_description IS
    'Catalogue entrys description';

COMMENT ON COLUMN catalogue.cata_publication_year IS
    'Catalogue entrys publication year';

COMMENT ON COLUMN catalogue.cata_edition IS
    'Catalogue entrys edition';

COMMENT ON COLUMN catalogue.cata_num_page IS
    'Catalogue entrys number of pages';

COMMENT ON COLUMN catalogue.cata_language IS
    'Catalogue entrys language';

COMMENT ON COLUMN catalogue.cata_note IS
    'Catalogue entrys note';

COMMENT ON COLUMN catalogue.publisher_code IS
    'Publisher code';

ALTER TABLE catalogue ADD CONSTRAINT catalogue_pk PRIMARY KEY ( cata_ddnum );

CREATE TABLE class (
    class_id      CHAR(4) NOT NULL,
    class_name    CHAR(1) NOT NULL,
    class_no_book NUMBER(3) NOT NULL
);

ALTER TABLE class
    ADD CONSTRAINT class_name_value CHECK ( class_name IN ( 'A', 'C', 'O' ) );

COMMENT ON COLUMN class.class_id IS
    'Id of class';

COMMENT ON COLUMN class.class_name IS
    'Name of class';

COMMENT ON COLUMN class.class_no_book IS
    'The number of days a book can be borrowed';

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( class_id );

CREATE TABLE isbn (
    isbn_value     CHAR(13) NOT NULL,
    isbn_book_type VARCHAR2(64) NOT NULL
);

COMMENT ON COLUMN isbn.isbn_value IS
    'ISBN digit';

COMMENT ON COLUMN isbn.isbn_book_type IS
    'Book type';

ALTER TABLE isbn ADD CONSTRAINT isbn_pk PRIMARY KEY ( isbn_value );

CREATE TABLE lga (
    lga_code              CHAR(10) NOT NULL,
    lga_name              VARCHAR2(256) NOT NULL,
    lga_contact_name      VARCHAR2(64) NOT NULL,
    lga_contact_phone_num CHAR(10) NOT NULL,
    lga_size              NUMBER(10, 2) NOT NULL
);

COMMENT ON COLUMN lga.lga_code IS
    'LGA code';

COMMENT ON COLUMN lga.lga_name IS
    'LGA name';

COMMENT ON COLUMN lga.lga_contact_name IS
    'LGA contact name';

COMMENT ON COLUMN lga.lga_contact_phone_num IS
    'LGA contact phone number';

COMMENT ON COLUMN lga.lga_size IS
    'LGA Size';

ALTER TABLE lga ADD CONSTRAINT lga_pk PRIMARY KEY ( lga_code );

CREATE TABLE loan (
    loan_num            CHAR(10) NOT NULL,
    book_num            CHAR(4) NOT NULL,
    loan_time           DATE NOT NULL,
    loan_due_date       DATE NOT NULL,
    load_return_date    DATE,
    loan_fine           NUMBER(10, 2),
    loan_fine_date_paid DATE,
    borrower_id         CHAR(4) NOT NULL,
    book_copy_num       CHAR(4) NOT NULL
);

COMMENT ON COLUMN loan.loan_num IS
    'Loan number - surrogate key';

COMMENT ON COLUMN loan.book_num IS
    'book number (surrogate PK)';

COMMENT ON COLUMN loan.loan_time IS
    'Loan time';

COMMENT ON COLUMN loan.loan_due_date IS
    'Load due date';

COMMENT ON COLUMN loan.load_return_date IS
    'Loan return date';

COMMENT ON COLUMN loan.loan_fine IS
    'Fine if any';

COMMENT ON COLUMN loan.loan_fine_date_paid IS
    'Fine date paid if any';

COMMENT ON COLUMN loan.borrower_id IS
    'Borrower ID';

COMMENT ON COLUMN loan.book_copy_num IS
    'book number (surrogate PK)';

ALTER TABLE loan ADD CONSTRAINT loan_pk PRIMARY KEY ( loan_num );

ALTER TABLE loan ADD CONSTRAINT loan_loan_time_un UNIQUE ( loan_time );

ALTER TABLE loan ADD CONSTRAINT loan_book_num_un UNIQUE ( book_num );

ALTER TABLE loan ADD CONSTRAINT loan_bc_num_l_time_un UNIQUE ( book_copy_num,
                                                               loan_time );

CREATE TABLE manager (
    manager_id         CHAR(10) NOT NULL,
    manager_first_name VARCHAR2(64) NOT NULL,
    manager_last_name  VARCHAR2(64) NOT NULL,
    manager_phone_no   CHAR(10) NOT NULL,
    branch_code        CHAR(3) NOT NULL
);

COMMENT ON COLUMN manager.manager_id IS
    'Manager id';

COMMENT ON COLUMN manager.manager_first_name IS
    'Manager first name';

COMMENT ON COLUMN manager.manager_last_name IS
    'Manager last  name';

COMMENT ON COLUMN manager.manager_phone_no IS
    'Manager phone number';

COMMENT ON COLUMN manager.branch_code IS
    'Branch Code';

CREATE UNIQUE INDEX manager__idx ON
    manager (
        branch_code
    ASC );

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( manager_id );

CREATE TABLE publisher (
    publisher_code CHAR(4) NOT NULL,
    publisher_name VARCHAR2(256 CHAR) NOT NULL
);

COMMENT ON COLUMN publisher.publisher_code IS
    'Publisher code';

COMMENT ON COLUMN publisher.publisher_name IS
    'Publishers name';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( publisher_code );

CREATE TABLE reserve (
    book_num      CHAR(4) NOT NULL,
    borrower_id   CHAR(4) NOT NULL,
    reserve_date  DATE NOT NULL,
    reserve_time  DATE NOT NULL,
    book_copy_num CHAR(4) NOT NULL
);

COMMENT ON COLUMN reserve.book_num IS
    'book number (surrogate PK)';

COMMENT ON COLUMN reserve.borrower_id IS
    'Borrower ID';

COMMENT ON COLUMN reserve.reserve_date IS
    'reserve date';

COMMENT ON COLUMN reserve.reserve_time IS
    'reserve time';

COMMENT ON COLUMN reserve.book_copy_num IS
    'book number (surrogate PK)';

ALTER TABLE reserve ADD CONSTRAINT reserve_pk PRIMARY KEY ( borrower_id,
                                                            book_copy_num );

CREATE TABLE subject (
    sub_id         CHAR(4) NOT NULL,
    sub_desription VARCHAR2(2048) NOT NULL
);

COMMENT ON COLUMN subject.sub_id IS
    'Subject ID';

COMMENT ON COLUMN subject.sub_desription IS
    'Subject description';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( sub_id );

ALTER TABLE book_copy
    ADD CONSTRAINT book_copy_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE book_copy
    ADD CONSTRAINT book_copy_isbn_fk FOREIGN KEY ( isbn_value )
        REFERENCES isbn ( isbn_value );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_class_fk FOREIGN KEY ( class_id )
        REFERENCES class ( class_id );

ALTER TABLE branch
    ADD CONSTRAINT branch_lga_fk FOREIGN KEY ( lga_code )
        REFERENCES lga ( lga_code );

ALTER TABLE branch
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( manager_id )
        REFERENCES manager ( manager_id );

ALTER TABLE cata_author
    ADD CONSTRAINT cata_author_author_fk FOREIGN KEY ( author_code )
        REFERENCES author ( author_code );

ALTER TABLE cata_author
    ADD CONSTRAINT cata_author_catalogue_fk FOREIGN KEY ( cata_ddnum )
        REFERENCES catalogue ( cata_ddnum );

ALTER TABLE cata_isbn
    ADD CONSTRAINT cata_isbn_catalogue_fk FOREIGN KEY ( cata_ddnum )
        REFERENCES catalogue ( cata_ddnum );

ALTER TABLE cata_isbn
    ADD CONSTRAINT cata_isbn_isbn_fk FOREIGN KEY ( isbn_value )
        REFERENCES isbn ( isbn_value );

ALTER TABLE cata_subject
    ADD CONSTRAINT cata_subject_catalogue_fk FOREIGN KEY ( cata_ddnum )
        REFERENCES catalogue ( cata_ddnum );

ALTER TABLE cata_subject
    ADD CONSTRAINT cata_subject_subject_fk FOREIGN KEY ( sub_id )
        REFERENCES subject ( sub_id );

ALTER TABLE catalogue
    ADD CONSTRAINT catalogue_publisher_fk FOREIGN KEY ( publisher_code )
        REFERENCES publisher ( publisher_code );

ALTER TABLE loan
    ADD CONSTRAINT loan_book_copy_fk FOREIGN KEY ( book_copy_num )
        REFERENCES book_copy ( book_copy_num );

ALTER TABLE loan
    ADD CONSTRAINT loan_borrower_fk FOREIGN KEY ( borrower_id )
        REFERENCES borrower ( borrower_id );

ALTER TABLE manager
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_book_copy_fk FOREIGN KEY ( book_copy_num )
        REFERENCES book_copy ( book_copy_num );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_borrower_fk FOREIGN KEY ( borrower_id )
        REFERENCES borrower ( borrower_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off